from typing import Protocol

from typing import Any, Protocol

from src.domain import (
    Brand,
    Category,
    OTP,
    User,
)


class UserRepository(Protocol):
    def save(self, user: User) -> None: ...
    def find_by_email(self, email: str) -> User | None: ...
    def find_by_id(self, id: str) -> User | None: ...


class OTPRepository(Protocol):
    def save(self, otp: OTP) -> None: ...
    def find_one(self, recipient: str, channel: str,
                 purpose: str) -> OTP | None: ...

    def delete(self, otp: OTP) -> None: ...


class BrandRepository(Protocol):
    def save(self, brand: Brand) -> None: ...
    def find_by_id(self, id: str) -> Brand | None: ...
    def find(self, params: dict[str, Any]) -> list[Brand]: ...
    def exists_by_name(self, name: str) -> bool: ...
    def delete(self, id: str) -> None: ...


class CategoryRepository(Protocol):
    def save(self, category: Category) -> None: ...
    def find(self, params: dict[str, Any]) -> list[Category]: ...
    def find_by_id(self, id: str) -> Category | None: ...
    def delete(self, ids: list[str]) -> None: ...
    def bulk_insert(self, categories: list[Category]) -> None: ...
