name: Build, Test & Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build App"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "My Value - ${{ github.ref_name }}."
      - name: Setup Go Env
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
      - run: go mod download
      - run: go build -o app .
      - run: ./app

  deploy:
    name: "Deploy to VPS"
    needs: build
    runs-on: ubuntu-latest