name: Build, Test & Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/telzz-ltd/erosync-api:latest
  CONTAINER: erosync-api

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        env:
          VPS_HOST: ${{ secrets.SERVER_HOST }}
          VPS_USER: ${{ secrets.SERVER_USER }}
          VPS_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_SSH_KEY" > ~/.ssh/vps_key
          chmod 600 ~/.ssh/vps_key

          ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/vps_key "$VPS_USER@$VPS_HOST" << 'EOF'
            set -e

            docker login ghcr.io \
              -u "${{ github.actor }}" \
              -p "${{ secrets.GITHUB_TOKEN }}"

            docker pull ghcr.io/telzz-ltd/erosync-api:latest

            docker stop erosync-api || true
            docker rm erosync-api || true

            docker run -d \
              --name erosync-api \
              --restart unless-stopped \
              -p 8000:8080 \
              ghcr.io/telzz-ltd/erosync-api:latest
          EOF